name: Create a GitHub release once a release PR is merged

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # Get the actual version and the previous one and use them to extract changelog lines between hashes
          # Use the changelog re-calculated to create a new release
          VERSION=$(grep -oP '^# \K[0-9.]*' CHANGELOG.md | head -n 1)
          OLD_VERSION=$(grep -oP '^# \K[0-9.]*' CHANGELOG.md | head -n 2 | tail -n 1)
          CHANGELOG=$(awk "/# ${VERSION}/,/# ${OLD_VERSION}/ {if ($0 != "" && $0 !~ /^# /) { print $0 }}") CHANGELOG.md
          gh release create ${VERSION} --draft --title ${VERSION} -n "${CHANGELOG}"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASEBOT_GITHUB_TOKEN }}
